import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import NavbarWithSearch from "@/components/shared/navbar/navbar";


const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-inter", // opcional pero recomendado
});

const neueHaas = localFont({
  src: [
    {
      path: '/fonts/NeueHaasDisplay-Mediu.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/NeueHaasDisplay-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-neue-haas', // <--- ESTA ES LA CLAVE
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${neueHaas.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
      >
        <NavbarWithSearch />
        {children}
      </body>
    </html>
  );
}
