// mocks/eventsMock.ts

export const agendaRapidaMock = [
  {
    id: 1,
    date: '2026-01-12',
    title: 'Muestra de arte contemporáneo',
    time: '19:00',
    slug: '2025-09-18-muestra-de-arte-contemporaneo',
    image: '/imagenes/expo.png',
  },
  {
    id: 2,
    date: '2026-01-08',
    title: 'Ciclo de cine nacional',
    time: '20:30',
    slug: '2025-09-19-ciclo-de-cine-nacional',
    image: '/imagenes/cine.png',
  },
  {
    id: 3,
    date: '2026-01-20',
    title: 'Concierto acústico – Artistas locales',
    time: '21:00',
    slug: '2025-09-20-concierto-acustico-artistas-locales',
    image: '/imagenes/noche-musica.webp',
  },
  {
    id: 4,
    date: '2025-09-21',
    title: 'Obra teatral: “La memoria del río”',
    time: '20:00',
    slug: '2025-09-21-obra-teatral-la-memoria-del-rio',
  },
  {
    id: 5,
    date: '2026-01-02',
    title: 'Concierto acústico – Artistas locales',
    time: '21:00',
    slug: '2025-09-20-concierto-acustico-artistas-locales',
    image: '/imagenes/noche-musica.webp',
  },
  // Mayo 2026
{
    id: 6,
    date: '2026-05-05',
    title: 'Cineclub TYÖ – "Very Important Perros"',
    time: '20:30',
    slug: '2026-05-05-very-important-perros',
    image: '/agenda/mayo/2026-05-05-very-important-perros.webp',
  },
  {
    id: 7,
    date: '2026-05-08',
    title: 'Llegar a una fiesta – Por Marina Barbera',
    time: '20:00',
    slug: '2026-05-08-llegar-a-una-fiesta',
    image: '/agenda/mayo/2026-05-08-llegar-a-una-fiesta.webp',
  },
  {
    id: 8,
    date: '2026-05-08',
    title: 'La máquina de hacer humo – La música que nos gusta',
    time: '22:30',
    slug: '2026-05-08-la-maquina-de-hacer-humo',
    image: '/agenda/mayo/2026-05-08-la-maquina-de-hacer-humo.webp',
  },
  {
    id: 9,
    date: '2026-05-09',
    title: 'Feria cultural / Agroecológica',
    time: '10:00',
    slug: '2026-05-09-feria-cultural-agroecologica',
    image: '/agenda/mayo/2026-05-09-feria-cultural-agroecologica.webp',
  },
  {
    id: 10,
    date: '2026-05-09',
    title: 'Celebración 54 años de CDC',
    time: '21:30',
    slug: '2026-05-09-celebracion-54-anos-cdc',
    image: '/agenda/mayo/2026-05-09-celebracion-54-anos-cdc.webp',
  },
{
    id: 11,
    date: "2026-05-10",
    title: "Cervantes se muestra – Danza",
    time: "18:30",
    slug: "2026-05-10-cervantes-se-muestra-danza",
    image: "/agenda/mayo/2026-05-10-cervantes-se-muestra-danza.webp",
  },

  // CATALEJO - Festival de Literatura Infantil y Juvenil
  {
    id: 12,
    date: "2026-05-15",
    title: "CATALEJO – Festival de Literatura Infantil y Juvenil",
    time: "09:00",
    slug: "catalejo-festival-literatura-infantil-juvenil",
    image: "/agenda/mayo/catalejo1.webp",
  },
  {
    id: 13,
    date: "2026-05-16",
    title: "CATALEJO – Festival de Literatura Infantil y Juvenil",
    time: "10:30",
    slug: "catalejo-festival-literatura-infantil-juvenil-sabado",
    image: "/agenda/mayo/catalejo1.webp",
  },
  {
    id: 14,
    date: "2026-05-17",
    title: "CATALEJO – Festival de Literatura Infantil y Juvenil",
    time: "11:00",
    slug: "catalejo-festival-literatura-infantil-juvenil-domingo",
    image: "/agenda/mayo/catalejo1.webp",
  },

  // Junio 2026 - Semana 22-27
  {
    id: 15,
    date: "2026-06-22",
    title: "Partido de Argentina vs Jordania",
    time: "14:00",
    slug: "argentina-vs-jordania-22-junio",
    image: "/agenda/junio/arg-vs-jordania.webp",
  },
  {
    id: 16,
    date: "2026-06-23",
    title: 'Cineclub TYÖ – "Perro Blanco" y "L\'Empire de Médor"',
    time: "20:30",
    slug: "cineclub-tyo-perro-blanco-empire-medor",
    image: "/agenda/junio/peliculas-de-perros.webp",
  },
  {
    id: 17,
    date: "2026-06-24",
    title: "Karaoke con Juanfer San Nicolas – Premios en efectivo",
    time: "21:30",
    slug: "karaoke-juanfer-san-nicolas",
    image: "/agenda/junio/karaoke-con-juanfer.webp",
  },
  {
    id: 18,
    date: "2026-06-26",
    title: "Retratos Musicales | Cuerdas Patagónicas - Filarmónica de Río Negro",
    time: "20:00",
    slug: "retratos-musicales-cuerdas-patagonicas",
    image: "/agenda/junio/retratos-musicales.webp",
  },
  {
    id: 19,
    date: '2026-06-27',
    title: 'Partido de Argentina vs Jordania',
    time: '23:00',
    slug: 'argentina-vs-jordania-27-junio',
    image: '/agenda/junio/arg-vs-jordania.webp',
  },

  // Julio 2026
  {
    id: 20,
    date: '2026-06-30',
    title: 'Cineclub TYÖ: "La Noche Está Marchándose Ya"',
    time: '20:30',
    slug: 'cineclub-tyo-la-noche-esta-marchandose-ya',
    image: '/agenda/junio/cine-cub-la-noche.webp',
  },
  {
    id: 21,
    date: '2026-07-01',
    title: 'Ciclo de peñas CDC: Fer Vazquez',
    time: '21:30',
    slug: 'ciclo-penas-cdc-fer-vazquez',
    image: '/agenda/julio/fer-vaszquez.webp',
  },
  {
    id: 22,
    date: '2026-07-03',
    title: 'Partido de Argentina vs Cabo Verde',
    time: '19:00',
    slug: 'argentina-vs-cabo-verde-03-julio',
    image: '/agenda/julio/arg-vs-cpv.webp',
  },
  {
    id: 23,
    date: '2026-07-04',
    title: 'Itinerario del pulso – Poesía y Música',
    time: '20:00',
    slug: 'itinerario-del-pulso-poesia-musica',
    image: '/agenda/julio/iti-del-impulso.webp',
  },
  // Julio 2026 (continuación)
  {
    id: 24,
    date: '2026-07-05',
    title: 'Animal o la Salida Humana – Luis Sartor',
    time: '20:00',
    slug: 'luis-sartor-animal-o-la-salida-humana',
    image: '/agenda/julio/animal-o.webp',
  },
  {
    id: 25,
    date: '2026-07-06',
    title: 'A Todo Ritmo – Just Dance Free',
    time: '21:00',
    slug: 'a-todo-ritmo-just-dance-free',
    image: '/agenda/julio/a-todo-ritmo.webp',
  },
  {
    id: 26,
    date: '2026-07-10',
    title: 'Pacientes en Espera',
    time: '20:00',
    slug: 'pacientes-en-espera',
    image: '/agenda/julio/de-ruben.webp',
  },
  {
    id: 27,
    date: '2026-07-18',
    title: 'Poder K-pop – Guerreras y Demonios',
    time: '15:00',
    slug: 'poder-kpop-guerreras-y-demonios',
    image: '/agenda/julio/KPOP-FEED-05.png',
  },
  {
    id: 28,
    date: '2026-07-18',
    title: 'Escuadrón al Rescate',
    time: '17:00',
    slug: 'escuadron-al-rescate',
    image: '/agenda/julio/ESCUADRON-FEED-05.png',
  },
  {
    id: 29,
    date: '2026-07-25',
    title: 'Adán y Eva "Un amor de aquellos"',
    time: '21:00',
    slug: 'adan-y-eva-un-amor-de-aquellos',
    image: '/agenda/julio/feed_25-07.png',
  },

  // Agosto 2026
  {
    id: 30,
    date: '2026-08-13',
    title: 'Cirko Marisko – "Monoargentum"',
    time: '21:00',
    slug: 'cirko-marisko-monoargentum',
    image: '/agenda/agosto/cirko-marisko.jpg',
  },
  {
    id: 31,
    date: '2026-08-22',
    title: 'Experiencia Dalia Gutmann – "No me calmo nada"',
    time: '21:00',
    slug: 'experiencia-dalia-gutmann-no-me-calmo-nada',
    image: '/agenda/agosto/no-me-calmo.png',
  },

  // Septiembre 2026
  {
    id: 32,
    date: '2026-09-26',
    title: 'Chaplin como nunca lo viste – Cineclub TYÖ + Ensamble XX-XXI',
    time: '20:00',
    slug: 'chaplin-como-nunca-lo-viste',
    image: '/agenda/septiembre/chaplin-como-nunca.png',
  },

  // Octubre 2026
  {
    id: 33,
    date: '2026-10-24',
    title: 'Juanpi González – "Oveja Negra"',
    time: '22:00',
    slug: 'juanpi-gonzalez-oveja-negra',
    image: '/agenda/octubre/OVEJA NEGRA FEED-08.png',
  },

  // Julio 2026 - Semana del 7 al 12
  {
    id: 34,
    date: '2026-07-07',
    title: 'Partido de Argentina vs Egipto',
    time: '13:00',
    slug: 'argentina-vs-egipto-07-julio',
    image: '/agenda/julio/arg-vs-egp.webp',
  },
  {
    id: 35,
    date: '2026-07-08',
    title: 'Ciclo de peñas CDC – Roy Orlando con Emilio Salas y Facundo Galarza',
    time: '21:30',
    slug: 'ciclo-penas-roy-orlando-emilio-salas-facundo-galarza',
    image: '/agenda/julio/rey-orlando.webp',
  },
  {
    id: 36,
    date: '2026-07-09',
    title: 'Las Rondas de Ley Primera 1ra edición – Con la participación de Aukiñ',
    time: '21:00',
    slug: 'las-rondas-ley-primera-aukin',
    image: '/agenda/julio/las-rondas-primera.webp',
  },
  {
    id: 37,
    date: '2026-07-10',
    title: 'Estudio En Dehors presenta "Esto lo resolvemos entre todos"',
    time: '21:00',
    slug: 'estudio-en-dehors-esto-lo-resolvemos',
    image: '/agenda/julio/dehors.webp',
  },
  {
    id: 38,
    date: '2026-07-11',
    title: 'Ciclo de peña CDC – Fer Vazquez y Victor Gonzalez',
    time: '22:30',
    slug: 'ciclo-penas-fer-vazquez-victor-gonzalez',
    image: '/agenda/julio/fer-vazquez.webp',
  },
  {
    id: 39,
    date: '2026-07-12',
    title: 'Feria Expo Viajera',
    time: '16:00',
    slug: 'feria-expo-viajera-julio-12',
    image: '/agenda/julio/expo-viajera.webp',
  },
]
