// mocks/eventsMock.ts

export const agendaRapidaMock = [
  {
    id: 1,
    date: '2026-01-12',
    title: 'Muestra de arte contemporáneo',
    time: '19:00',
    slug: '2025-09-18-muestra-de-arte-contemporaneo',
    image: '/imagenes/expo.png',
  },
  {
    id: 2,
    date: '2026-01-08',
    title: 'Ciclo de cine nacional',
    time: '20:30',
    slug: '2025-09-19-ciclo-de-cine-nacional',
    image: '/imagenes/cine.png',
  },
  {
    id: 3,
    date: '2026-01-20',
    title: 'Concierto acústico – Artistas locales',
    time: '21:00',
    slug: '2025-09-20-concierto-acustico-artistas-locales',
    image: '/imagenes/noche-musica.webp',
  },
  {
    id: 4,
    date: '2025-09-21',
    title: 'Obra teatral: “La memoria del río”',
    time: '20:00',
    slug: '2025-09-21-obra-teatral-la-memoria-del-rio',
  },
  {
    id: 5,
    date: '2026-01-02',
    title: 'Concierto acústico – Artistas locales',
    time: '21:00',
    slug: '2025-09-20-concierto-acustico-artistas-locales',
    image: '/imagenes/noche-musica.webp',
  },
  // Mayo 2026
{
    id: 6,
    date: '2026-05-05',
    title: 'Cineclub TYÖ – "Very Important Perros"',
    time: '20:30',
    slug: '2026-05-05-very-important-perros',
    image: '/agenda/mayo/2026-05-05-very-important-perros.webp',
  },
  {
    id: 7,
    date: '2026-05-08',
    title: 'Llegar a una fiesta – Por Marina Barbera',
    time: '20:00',
    slug: '2026-05-08-llegar-a-una-fiesta',
    image: '/agenda/mayo/2026-05-08-llegar-a-una-fiesta.webp',
  },
  {
    id: 8,
    date: '2026-05-08',
    title: 'La máquina de hacer humo – La música que nos gusta',
    time: '22:30',
    slug: '2026-05-08-la-maquina-de-hacer-humo',
    image: '/agenda/mayo/2026-05-08-la-maquina-de-hacer-humo.webp',
  },
  {
    id: 9,
    date: '2026-05-09',
    title: 'Feria cultural / Agroecológica',
    time: '10:00',
    slug: '2026-05-09-feria-cultural-agroecologica',
    image: '/agenda/mayo/2026-05-09-feria-cultural-agroecologica.webp',
  },
  {
    id: 10,
    date: '2026-05-09',
    title: 'Celebración 54 años de CDC',
    time: '21:30',
    slug: '2026-05-09-celebracion-54-anos-cdc',
    image: '/agenda/mayo/2026-05-09-celebracion-54-anos-cdc.webp',
  },
{
    id: 11,
    date: "2026-05-10",
    title: "Cervantes se muestra – Danza",
    time: "18:30",
    slug: "2026-05-10-cervantes-se-muestra-danza",
    image: "/agenda/mayo/2026-05-10-cervantes-se-muestra-danza.webp",
  },

  // CATALEJO - Festival de Literatura Infantil y Juvenil
  {
    id: 12,
    date: "2026-05-15",
    title: "CATALEJO – Festival de Literatura Infantil y Juvenil",
    time: "09:00",
    slug: "catalejo-festival-literatura-infantil-juvenil",
    image: "/agenda/mayo/catalejo1.webp",
  },
  {
    id: 13,
    date: "2026-05-16",
    title: "CATALEJO – Festival de Literatura Infantil y Juvenil",
    time: "10:30",
    slug: "catalejo-festival-literatura-infantil-juvenil-sabado",
    image: "/agenda/mayo/catalejo1.webp",
  },
  {
    id: 14,
    date: "2026-05-17",
    title: "CATALEJO – Festival de Literatura Infantil y Juvenil",
    time: "11:00",
    slug: "catalejo-festival-literatura-infantil-juvenil-domingo",
    image: "/agenda/mayo/catalejo1.webp",
  },

  // Junio 2026 - Semana 22-27
  {
    id: 15,
    date: "2026-06-22",
    title: "Partido de Argentina vs Jordania",
    time: "14:00",
    slug: "argentina-vs-jordania-22-junio",
    image: "/agenda/junio/arg-vs-jordania.webp",
  },
  {
    id: 16,
    date: "2026-06-23",
    title: 'Cineclub TYÖ – "Perro Blanco" y "L\'Empire de Médor"',
    time: "20:30",
    slug: "cineclub-tyo-perro-blanco-empire-medor",
    image: "/agenda/junio/peliculas-de-perros.webp",
  },
  {
    id: 17,
    date: "2026-06-24",
    title: "Karaoke con Juanfer San Nicolas – Premios en efectivo",
    time: "21:30",
    slug: "karaoke-juanfer-san-nicolas",
    image: "/agenda/junio/karaoke-con-juanfer.webp",
  },
  {
    id: 18,
    date: "2026-06-26",
    title: "Retratos Musicales | Cuerdas Patagónicas - Filarmónica de Río Negro",
    time: "20:00",
    slug: "retratos-musicales-cuerdas-patagonicas",
    image: "/agenda/junio/retratos-musicales.webp",
  },
  {
    id: 19,
    date: "2026-06-27",
    title: "Partido de Argentina vs Jordania",
    time: "23:00",
    slug: "argentina-vs-jordania-27-junio",
    image: "/agenda/junio/arg-vs-jordania.webp",
  },
]
